### PR TITLE
Add macOS support.

### PR DESCRIPTION
**Pull request by jmmanos**
Tested with macOS 11.1 and clang 12.0.0.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks @jmmanos.

We do not officially support macOS yet, but this PR is a welcome addition anyway.

Did you test that it actually works on  macOS or does it just compile?

**Comment by fmonpelat** [comment]
@jmmanos tried using your modifications to compile, it did successfully but using the c example (executing version option = v)prints:
`[2021-03-12 17:22:13.326] [debug] [UnixSerial] Opening serial port /dev/tty.usbmodem00_00_013 type usb baudrate 115200
[2021-03-12 17:22:13.332] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 17:22:13.343] [debug] [PacketSender] Waiting packet..
[2021-03-12 17:22:13.344] [error] [PacketSender] Protocol version doesn't match. Expected: 2, Received: 118
[2021-03-12 17:22:13.344] [error] [DeviceControllerImpl] Failed receiving data packet (status 107)
Error trying to query firmware version. Status: 104 (VersionMismatch)
`
did it ocurr to you?

**Comment by jmmanos** [comment]
I apologize for the delayed response @gabime, I verified that it both built and worked on my Intel-based Mac. I have not tested it on an M1 Mac but that might be me getting a little ahead of myself with Mac support. 

@fmonpelat I am able to use both the c and cpp version of the sample code to execute the more info option 'v'. Here is the output for the rsid_c_example that I get:
```
[2021-03-12 18:27:16.519] [debug] [UnixSerial] Opening serial port /dev/tty.usbmodem00_00_013 type usb baudrate 115200
[2021-03-12 18:27:16.523] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.535] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.535] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.535] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.547] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.547] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.547] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.560] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.560] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.560] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.571] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.571] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.571] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.582] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.582] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.583] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.593] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.593] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.593] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.605] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.605] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.605] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.617] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.618] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.618] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:27:16.630] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.630] [debug] [PacketSender] Received packet 'v' after 0 millis
[2021-03-12 18:27:16.630] [debug] [PacketSender] Sending packet 'i'
[2021-03-12 18:27:16.640] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:27:16.640] [debug] [PacketSender] Received packet 'i' after 0 millis

Additional information:
 * S/N: 10446228067099A27FM10464-100
 * Firmware: NNLED:2.22.21.0|NNLAS:2.12.21.0|DNET:4.5.20.0|YOLO:26.2.21.0|AS2DLR:23.2.21.0|RECOG:1.2.21.0|SCRAP:0.0.0.0|OPFW:2.0.10.45
 * Host: 0.12.4
```

**Comment by jmmanos** [comment]
@fmonpelat After pulling the most recent commits into my local repo I am now encountering a new issue. Here is the output when I run the additional info command 'v':
```
[2021-03-12 18:56:51.118] [debug] [UnixSerial] Opening serial port /dev/tty.usbmodem00_00_013 type usb baudrate 115200
[2021-03-12 18:56:51.121] [debug] [PacketSender] Sending packet 'v'
[2021-03-12 18:56:51.133] [debug] [PacketSender] Waiting packet..
[2021-03-12 18:56:56.133] [debug] [UnixSerial] Timeout recv 2 bytes. Got only 0 bytes
[2021-03-12 18:56:56.133] [error] [PacketSender] Failed to recv packet crc (2 bytes)
[2021-03-12 18:56:56.133] [error] [DeviceControllerImpl] Failed receiving data packet (status 103)
Error trying to query firmware version. Status: 102 (SerialError)
```

Debugging serial communication is always fun, I'm looking into it!

**Comment by ShravyaB** [comment]
@jmmanos There was a new release 15 days back and a new firmware version was released? Did you update it? Are you getting the issue before or after updating?

**Pull request closed without merging**
